export const ADD_GROCERY = "ADD_GROCERY";
export const REMOVE_SHOPPING_ITEM = "REMOVE_SHOPPING_ITEM";
export const ADD_POCKET_MONEY = "ADD_POCKET_MONEY";
export const REMOVE_POCKET_MONEY = "REMOVE_POCKET_MONEY";